name: Issue Branch & Commit Generator

on:
  issues:
    types: [opened, edited]

jobs:
  generate-comment:
    # 이슈가 열리거나 제목이 수정된 경우에만 실행
    if: github.event.action == 'opened' || (github.event.action == 'edited' && github.event.changes.title)
    runs-on: ubuntu-latest

    steps:
      - name: Generate Branch & Commit Comment
        uses: Chuseok22/github-issue-commnet-generator@v1
        with:
          # GitHub 토큰 (Public repo는 GITHUB_TOKEN, Private repo는 Personal Access Token 사용)
          token: ${{ secrets.GITHUB_TOKEN }}

          # 브랜치 접두사 설정 (예: feat/, bugfix/, feature/ 등)
          branch_prefix: "feat/"

          # 브랜치명 최대 길이 (prefix 제외)
          max_branch_length: 100

          # 커밋 메시지 템플릿 (${변수명} 형태로 사용)
          commit_template: "${issueTitle} : feat : {변경 사항에 대한 설명} ${issueUrl}"

          # 댓글 업데이트를 위한 마커 (기본값 사용 권장)
          comment_marker: "<!-- issue-normalizer -->"
